# Generated by Django 3.0.4 on 2020-03-17 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EinkaufsApp', '0003_einkauf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einkaufsauftrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachricht', models.TextField(default='Nachricht an die Helfer', max_length=200)),
                ('liste_text', models.TextField(default='Einkaufsliste hier eintragen', max_length=500)),
                ('telefonnummer', models.TextField(default='06222000000', help_text='Telefonnummer hier eintragen. Ihre Nummer wird nur an die HelferIn übermittelt, die ihren Einkauf tätigen möchte.', max_length=25)),
                ('budget', models.CharField(default='30', max_length=4)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_done', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AKT', 'aktiv'), ('ANG', 'angenommen'), ('DEF', 'default'), ('ABG', 'abgeschlossen')], default='default', max_length=13)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auftraege', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Einkauf',
        ),
    ]
