# Generated by Django 3.0.4 on 2020-03-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EinkaufsApp', '0003_einkauf'),
    ]

    operations = [
        migrations.AddField(
            model_name='einkauf',
            name='telefonnummer',
            field=models.TextField(default='06222000000', help_text='Telefonnummer hier eintragen. Ihre Nummer wird nur an die HelferIn übermittelt, die ihren Einkauf tätigen möchte.', max_length=25),
        ),
        migrations.AlterField(
            model_name='einkauf',
            name='budget',
            field=models.CharField(default='30', max_length=4),
        ),
        migrations.AlterField(
            model_name='einkauf',
            name='liste_text',
            field=models.TextField(default='Einkaufsliste hier eintragen', max_length=500),
        ),
        migrations.AlterField(
            model_name='einkauf',
            name='nachricht',
            field=models.TextField(default='Nachricht an die Helfer', max_length=200),
        ),
    ]
