# Generated by Django 3.0.4 on 2020-03-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EinkaufsApp', '0004_auto_20200318_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='einkaufsauftrag',
            old_name='working_on_user_id',
            new_name='working_on_user',
        ),
    ]
